# Generated by Django 3.2.12 on 2022-04-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20220428_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
