# Generated by Django 3.2.12 on 2022-04-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_modelproduct_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelproduct',
            name='upload_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='modelproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
