# Generated by Django 3.2.12 on 2022-04-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20220429_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
